### PR TITLE
Development

### PR DESCRIPTION
**Pull request by Aaron-RN**

### CODE REVIEW

**Comment by Torres-ssf** [comment]
Hi there @Aaron-RN 
Please let me ask you, did you do collaborative work in this project? I'm seeing that all commits were done by you and this project was supposed to be done with your coding partner.
Before merge this project to master we need to do some changes to make it in line with Microverse guidelines.

- [ ] Microverse guidelines require that you use a separate CSS file for styling. This the best practice. Please kindly remove all styling from your HTML code, both from your head tag as well the other ones, and place it on a separated CSS file.

- [ ] Its best practice to use the nav tag for the navbar. I would recommend you to make your `div class="navbar"` a nav tag instead.

- [ ] You should use a button tag for the search button.

- [ ] The video must have a separated container (div or similar)

- [ ] Its best practice to use the main tag for the main content of your page. In this project's case, the video and his description and comments.

Please kindly make these changes and submit for code review again. Happy coding.

**Comment by Aaron-RN** [comment]
> Hi there @Aaron-RN
> Please let me ask you, did you do collaborative work in this project? I'm seeing that all commits were done by you and this project was supposed to be done with your coding partner.
> Before merge this project to master we need to do some changes to make it in line with Microverse guidelines.
> 
> * [ ]  Microverse guidelines require that you use a separate CSS file for styling. This the best practice. Please kindly remove all styling from your HTML code, both from your head tag as well the other ones, and place it on a separated CSS file.
> * [ ]  Its best practice to use the nav tag for the navbar. I would recommend you to make your `div class="navbar"` a nav tag instead.
> * [ ]  You should use a button tag for the search button.
> * [ ]  The video must have a separated container (div or similar)
> * [ ]  Its best practice to use the main tag for the main content of your page. In this project's case, the video and his description and comments.
> 
> Please kindly make these changes and submit for code review again. Happy coding.

Yeah the reason it looked like I did all the work was because we moved this from the old repository to this new one. We were doing all the projects in one repository at first.

**Comment by Ispirett** [comment]
Great work on some of the changes  :100:  also you project looks really good I almost thought I opened youtube lol :v: There are styles some changes to be made.
- [ ] There are still "styles" attributes in your HTML also known as inline styling. Please put css styles in 
in the css file 
- [ ]  On line 39 in the iframe tag there the width value should be 90 and not 90%
- [ ] The frameborder attribute on the iframe element is obsolete. Use CSS instead on line 39

When finished resubmit for review Thanks

**Comment by Torres-ssf** [comment]
### Great work team 👍
You can merge to master now. Don't forget to submit the form.
Good luck on the next project

**Pull request merged**
